### PR TITLE
Migrate to Go Dep

### PR DESCRIPTION
**Pull request by zparnold**
Hey there! I'm going to be working on a `list_of_map` style addition here in a moment. Go Dep is generally accepted standard for dependency management. (Or at least it was in my other projects 😄 )

So I figured I would toss this in. LMK if you're not interested @Ashald

### CODE REVIEW

**Comment by ashald** [comment]
I'm not an expert in Go and I just failed to figure out how to use `Go Dep` properly. 😞

It' be great to move to it as I understand it seem to be "the future" but I'd highly appreciate if you could update readme to include few instructions for noobs like myself how to use it. I'm not asking for a complete and thoroughful guide but just few basic commands like that would replace `govendor init` and `govendor fetch +m`. 🙂

Thanks!

P.S.: As for `list_of_map` - frankly I'm not sure if that can be implemented right now (depending on what you have in mind) given restrictions in HCL (https://www.terraform.io/docs/extend/schemas/schema-types.html#typelist). On the other hand, to the best of my knowledge `HCL 2` is coming out really soon (I'd expect its release to be announced on October 23 at HashiConf) and I think it should add support for schemas of arbitrary complexity.

**Comment by zparnold** [comment]
I think you are totally right 😂 and I had to give up. 😄 But in the meantime here is some of the commands for godep
```
Dep is a tool for managing dependencies for Go projects

Usage: "dep [command]"

Commands:

  init     Set up a new Go project, or migrate an existing one
  status   Report the status of the project's dependencies
  ensure   Ensure a dependency is safely vendored in the project
  version  Show the dep version information
  check    Check if imports, Gopkg.toml, and Gopkg.lock are in sync

Examples:
  dep init                               set up a new project
  dep ensure                             install the project's dependencies
  dep ensure -update                     update the locked versions of all dependencies
  dep ensure -add github.com/pkg/errors  add a dependency to the project

Use "dep help [command]" for more information about a command.
```

**Comment by zparnold** [comment]
So what I did was `dep init` and then `dep ensure` and that's it!

**Comment by ashald** [comment]
I guess what was confusing to me is that `dep` seems to take way more time and space and I was not sure I understand reasons for that and that I actually need what it's doing. It seems that it resolves all dependencies transitively and tries to cache them all?

On MBP2018 4.5 GHZ, `govendor init && govendor fetch +m` takes 1s while `dep init` took 1 minute.

I'm not against `dep` I just want to be sure it's really a proper tool in this case. 🙂

**Comment by zparnold** [comment]
Yea, I see what you mean. Not sure exactly how the dependency resolution of `go dep` works. But seems like `govendor` is clearly more performant. And the more I mess with HCL it seems to be the standard for terraform plugins, so I think it's not worth it.

**Pull request closed without merging**
